version: '3.8'
services:
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_LOGIN: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
    volumes:
      - db-data:/var/lib/mysql:rw
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/store:delegated
    links:
      - db
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/store"
      APP_URL: "http://store.local:8099"
      APP_ENV: "dev"
      APP_SECRET: "b6275207a0c9efcb064a69b938501b3e"
      APP_HOSTNAME: "store.local"
  nginx:
    image: nginx:1.19
    ports:
      - "8099:80"
    volumes:
      - .:/var/www/store:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
volumes:
  db-data: